chore: Add missing env var to run-testnet commands (#3055)
# Description

- Add missing `SCAN_L1_START_HEIGHT` var to `run-testnet.md`.
`RunnerConfig` wasn't properly parsed from env and ended up panicking
with `"message":"thread 'main' panicked at 'Runner config is missing'`